export enum AppCategory {
  DeFi = "DeFi",
  Gaming = "Gaming",
  NFT = "NFT",
  Consumer = "Consumer",
};

export const AppList = [
  {
    name: "Superswap",
    category: AppCategory.DeFi,
    icon: "",
    banner: "",
    visits: "0",
    link: "/superswap",
    bp: "1026_001",
    bpContent: "superswap",
    isSpotlight: true,
    isOutlink: false,
    description: "",
  },
  {
    name: "Superbridge",
    category: AppCategory.DeFi,
    icon: "",
    banner: "",
    visits: "0",
    link: "/bridge",
    bp: "1026_001",
    bpContent: "superbridge",
    isSpotlight: true,
    isOutlink: false,
    description: "",
  },
  {
    name: "Kuru Exchange",
    category: AppCategory.DeFi,
    icon: "/images/mainnet/discover/dapps/kuru-min.png",
    banner: "/images/mainnet/discover/banner-kuru.png",
    visits: "0",
    link: "https://x.com/KuruExchange",
    bp: "1026_001",
    bpContent: "kuru-exchange",
    isSpotlight: true,
    isOutlink: true,
    description: "Find and trade your favourite coins on a fully on-chain order book",
  },
  {
    name: "Magma Staking",
    category: AppCategory.DeFi,
    icon: "/images/mainnet/discover/dapps/magma-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/MagmaStaking",
    bp: "1026_001",
    bpContent: "magma-staking",
    isSpotlight: true,
    isOutlink: true,
    description: "Magma is a community-driven liquid staking protocol for the Monad blockchain, offering MEV-boosted yields via gMON tokens",
  },
  {
    name: "Monorail",
    category: AppCategory.DeFi,
    icon: "/images/mainnet/discover/dapps/monorail-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/monorail_xyz",
    bp: "1026_001",
    bpContent: "monorail",
    isSpotlight: true,
    isOutlink: true,
    description: "Monorail is a DeFi aggregator that merges AMMs and orderbooks into a single, unified liquidity system called Synthetic Orderbooks",
  },
  {
    name: "FastLane",
    category: AppCategory.DeFi,
    icon: "/images/mainnet/discover/dapps/fastlane-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/0xFastLane",
    bp: "1026_001",
    bpContent: "fastlane",
    isSpotlight: false,
    isOutlink: true,
    description: "FastLane on Monad Docs introduces tools for optimizing blockchain execution, automation, and staking on Monad, aiming to improve transaction predictability and usability",
  },
  {
    name: "Alloca",
    category: AppCategory.DeFi,
    icon: "/images/mainnet/discover/dapps/alloca-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/alloca_xyz",
    bp: "1026_001",
    bpContent: "alloca",
    isSpotlight: false,
    isOutlink: true,
    description: "Alloca is a launchpad for projects on Monad, offering customizable fundraising, tiered access, and NFT-based rewards",
  },
  {
    name: "Drake Exchange",
    category: AppCategory.DeFi,
    icon: "/images/mainnet/discover/dapps/drake-echange-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/DrakeExchange",
    bp: "1026_001",
    bpContent: "drake-exchange",
    isSpotlight: false,
    isOutlink: true,
    description: "The protocol routes orders to an on-chain CLOB for competitive pricing, falling back to liquidity vaults for guaranteed fills when orderbook depth is insufficient",
  },
  {
    name: "Seer Trade",
    category: AppCategory.DeFi,
    icon: "/images/mainnet/discover/dapps/seer-trad-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/seertrade",
    bp: "1026_001",
    bpContent: "seer-trade",
    isSpotlight: false,
    isOutlink: true,
    description: "Combine social and onchain intelligence to research, discover and trade all in one place.",
  },
  {
    name: "Monday Trade",
    category: AppCategory.DeFi,
    icon: "/images/mainnet/discover/dapps/monday-trade-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/MondayTrade_",
    bp: "1026_001",
    bpContent: "monday-trade",
    isSpotlight: false,
    isOutlink: true,
    description: "Monday Trade is a lightning-fast, gamified decentralized exchange (DEX) on Monad, designed for instant, cost-efficient trading with a user-friendly experience",
  },
  {
    name: "Nad.fun",
    category: AppCategory.DeFi,
    icon: "/images/mainnet/discover/dapps/nad.fun-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/naddotfun",
    bp: "1026_001",
    bpContent: "nad-fun",
    isSpotlight: false,
    isOutlink: true,
    description: "Social Memecoin Playground powered by Monad",
  },
  {
    name: "Timeswap",
    category: AppCategory.DeFi,
    icon: "/images/mainnet/discover/dapps/timeswap-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/TimeswapLabs",
    bp: "1026_001",
    bpContent: "timeswap",
    isSpotlight: true,
    isOutlink: true,
    description: "Timeswap is a permissionless, oracleless AMM-based money market enabling fixed-maturity lending/borrowing for any ERC‑20 across multiple chains, with non-liquidatable loans and isolated risk pools",
  },
  {
    name: "Space Invaders",
    category: AppCategory.Gaming,
    icon: "/images/mainnet/discover/avatar-space-invaders.png",
    banner: "/images/mainnet/discover/banner-space-invaders.png",
    visits: "0",
    link: "/arcade/space-invaders",
    bp: "1026_001",
    bpContent: "space",
    isSpotlight: true,
    isOutlink: false,
    description: "Attacked or Escape! Bet MON. Cash out. Repeat.",
  },
  {
    name: "Lucky 777",
    category: AppCategory.Gaming,
    icon: "/images/mainnet/discover/avatar-lucky-777.png",
    banner: "/images/mainnet/discover/banner-lucky-777.png",
    visits: "0",
    link: "/arcade/lucky777",
    bp: "1026_001",
    bpContent: "lucky777",
    isSpotlight: true,
    isOutlink: false,
    description: "Spin! Spin! Spin! Earn MON or NFTs by the easiest way",
  },
  {
    name: "Chart Voyager",
    category: AppCategory.Gaming,
    icon: "/images/mainnet/chart-voyager.png",
    banner: "",
    visits: "0",
    link: "/arcade/chart-voyager",
    bp: "1026_001",
    bpContent: "rps",
    isSpotlight: true,
    isOutlink: false,
    description: "Tap. Predict. Earn, Touch the future",
  },
  // {
  //   name: "Guess Who",
  //   category: AppCategory.Gaming,
  //   icon: "/images/mainnet/guess-who.png",
  //   banner: "",
  //   visits: "0",
  //   link: "/arcade/guess-who",
  //   bp: "1026_001",
  //   bpContent: "rps",
  //   isSpotlight: false,
  //   isOutlink: false,
  //   description: "Can you guess who this is?",
  // },
  {
    name: "Lumiterra",
    category: AppCategory.Gaming,
    icon: "/images/mainnet/discover/dapps/lumiterra-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/LumiterraGame",
    bp: "1026_001",
    bpContent: "lumiterra",
    isSpotlight: false,
    isOutlink: true,
    description: "Lumonad is a gamified campaign by Lumiterra and Monad, where users collect daily \"Lemons\" and unlock exclusive digital costumes by holding specific tokens or NFTs.",
  },
  {
    name: "Omnia",
    category: AppCategory.Gaming,
    icon: "/images/mainnet/discover/dapps/omnia-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/ExploreOmnia",
    bp: "1026_001",
    bpContent: "omnia",
    isSpotlight: false,
    isOutlink: true,
    description: "Omnia is an upcoming pet battle adventure by Sappy, actively playtesting and integrating Monad",
  },
  {
    name: "ME on Monad",
    category: AppCategory.NFT,
    icon: "/images/mainnet/discover/dapps/me-on-monad-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/MEonMonad",
    bp: "1026_001",
    bpContent: "me-on-monad",
    isSpotlight: false,
    isOutlink: true,
    description: "The leading NFTs trading & minting platform on Monad",
  },
  {
    name: "Lil Stars",
    category: AppCategory.NFT,
    icon: "/images/mainnet/discover/dapps/lil-stars-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/lilstarrrs",
    bp: "1026_001",
    bpContent: "lil-stars",
    isSpotlight: true,
    isOutlink: true,
    description: "Lil Chogstars & friends. Lilstars' official collection account stored on Monad for everything lilchogstarsand friends.",
  },
  {
    name: "Chog NFT",
    category: AppCategory.NFT,
    icon: "/images/mainnet/discover/dapps/chog-nft-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/ChogNFT",
    bp: "1026_001",
    bpContent: "chog-nft",
    isSpotlight: true,
    isOutlink: true,
    description: "Chog is one of the first memes to emerge from the Monad community",
  },
  {
    name: "BlockNads",
    category: AppCategory.NFT,
    icon: "/images/mainnet/discover/dapps/blocknads-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/BlockNads",
    bp: "1026_001",
    bpContent: "blocknads",
    isSpotlight: false,
    isOutlink: true,
    description: "A paradigm shift. The new order of defiance. An exclusive circle of explorers. Anon, do you even explore?. ",
  },
  {
    name: "Spiky",
    category: AppCategory.NFT,
    icon: "/images/mainnet/discover/dapps/spiky-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/spiky_xyz",
    bp: "1026_001",
    bpContent: "spiky",
    isSpotlight: false,
    isOutlink: true,
    description: "meet Spiky - the sharp edge of pixel art NFTs on monad",
  },
  {
    name: "Monadverse",
    category: AppCategory.NFT,
    icon: "/images/mainnet/discover/dapps/monadverse-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/monadverse",
    bp: "1026_001",
    bpContent: "monadverse",
    isSpotlight: false,
    isOutlink: true,
    description: "A cultural movement featuring monanimals on monad. For the Nads, By the Nads",
  },
  {
    name: "Skrumpeys",
    category: AppCategory.NFT,
    icon: "/images/mainnet/discover/dapps/skrumpeys-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/skrumpeys",
    bp: "1026_001",
    bpContent: "skrumpeys",
    isSpotlight: false,
    isOutlink: true,
    description: "🟣💫 skrumpeys 💜🍬 a whimsical PFP project. only on monad☉",
  },
  {
    name: "Mondana Baddies",
    category: AppCategory.NFT,
    icon: "/images/mainnet/discover/dapps/Mondana-Baddies-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/mondanabaddies",
    bp: "1026_001",
    bpContent: "mondana-baddies",
    isSpotlight: false,
    isOutlink: true,
    description: "mondana - a digital art & NFT brand on monad",
  },
  {
    name: "Monshape",
    category: AppCategory.NFT,
    icon: "/images/mainnet/discover/dapps/Monshape-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/Monshape",
    bp: "1026_001",
    bpContent: "monshape",
    isSpotlight: false,
    isOutlink: true,
    description: "Monshape is a community-driven NFT project where six characters come to life through art, stories, and real holder utilities.",
  },
  {
    name: "Real Nads Club",
    category: AppCategory.NFT,
    icon: "/images/mainnet/discover/dapps/Real-Nads-Club-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/RealNadsClub",
    bp: "1026_001",
    bpContent: "real-nads-club",
    isSpotlight: false,
    isOutlink: true,
    description: "Build with Real , Connect with Nads",
  },
  {
    name: "The 10k Squad",
    category: AppCategory.NFT,
    icon: "/images/mainnet/discover/dapps/The-10k-Squad-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/the10kSquad",
    bp: "1026_001",
    bpContent: "the-10k-squad",
    isSpotlight: false,
    isOutlink: true,
    description: "hand drawn NFT project on monad",
  },
  {
    name: "llamao",
    category: AppCategory.NFT,
    icon: "/images/mainnet/discover/dapps/llamao-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/llamao_",
    bp: "1026_001",
    bpContent: "llamao",
    isSpotlight: false,
    isOutlink: true,
    description: "A mindfulness-first IP brand building a wellness ecosystem focused on calm, clarity, and balance",
  },
  {
    name: "KINETK AI",
    category: AppCategory.Consumer,
    icon: "/images/mainnet/discover/dapps/KINETK-AI-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/KINETK_AI",
    bp: "1026_001",
    bpContent: "kinetk-ai",
    isSpotlight: false,
    isOutlink: true,
    description: "KINETK is an AI tool for creators that tracks content across the internet and alerts instantly when it appears anywhere.",
  },
  {
    name: "Levr Bet",
    category: AppCategory.Consumer,
    icon: "/images/mainnet/discover/dapps/Levr-Bet-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/Levr_Bet",
    bp: "1026_001",
    bpContent: "levr-bet",
    isSpotlight: false,
    isOutlink: true,
    description: "Levr Bet is a crypto sports betting platform offering leveraged bets (up to 5x) and real-time, on-chain betting with lower fees, targeting DeFi users",
  },
  {
    name: "Kizzy Mobile",
    category: AppCategory.Consumer,
    icon: "/images/mainnet/discover/dapps/Kizzy-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/kizzymobile",
    bp: "1026_001",
    bpContent: "kizzy-mobile",
    isSpotlight: false,
    isOutlink: true,
    description: "Kizzy is a platform for social media betting, allowing users to wager on trending online content and personalities, built on the Monad blockchain.",
  },
  {
    name: "RareBet Sports",
    category: AppCategory.Consumer,
    icon: "/images/mainnet/discover/dapps/RareBet-Sports-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/RareBetSports",
    bp: "1026_001",
    bpContent: "rarebet-sports",
    isSpotlight: false,
    isOutlink: true,
    description: "RareBetSports is a Web3 daily fantasy sports platform where users pick over/under outcomes and can win up to 100x their crypto entry, powered by smart contracts and on-chain data.",
  },
  {
    name: "Lootgo",
    category: AppCategory.Consumer,
    icon: "/images/mainnet/discover/dapps/Lootgo-min.png",
    banner: "",
    visits: "0",
    link: "https://x.com/lootgo_official",
    bp: "1026_001",
    bpContent: "lootgo",
    isSpotlight: false,
    isOutlink: true,
    description: "LootGO is a free walk-to-earn mobile app that gamifies daily movement by turning it into a treasure hunt for rewards.",
  },
];
