export enum AppCategory {
  Gaming = "Gaming",
  Dex = "Dex",
  Staking = "Staking",
  NFT = "NFT",
  PredictionMarket = "Prediction",
  Lending = "Lending",
};

export const AppList = [
  {
    name: "Kuru",
    category: AppCategory.Dex,
    icon: "/images/mainnet/discover/avatar-kuru.png",
    banner: "/images/mainnet/discover/banner-kuru.png",
    visits: "0",
    link: "https://www.kuru.io",
    bp: "1026_001",
    bpContent: "kuru",
    isSpotlight: true,
    description: "Kuru is a fully on-chain order book exchange built on Monad. Kuru is trying to close the gap between decentralized and centralized exchanges. Users will get the best of both worlds with slippage, self-custody and composability.",
  },
  {
    name: "Space Invaders",
    category: AppCategory.Gaming,
    icon: "/images/mainnet/discover/avatar-space-invaders.png",
    banner: "/images/mainnet/discover/banner-space-invaders.png",
    visits: "0",
    link: "/arcade/space-invaders",
    bp: "1026_001",
    bpContent: "space",
    isSpotlight: true,
    description: "Attacked or Escape! Bet MON. Cash out. Repeat.",
  },
  {
    name: "aPriori",
    category: AppCategory.Staking,
    icon: "/images/mainnet/discover/avatar-apriori.png",
    banner: "/images/mainnet/discover/banner-apriori.png",
    visits: "0",
    link: "https://www.apr.io",
    bp: "1026_001",
    bpContent: "apriori",
    isSpotlight: true,
    description: "aPriori is the leading MEV-powered liquid staking platform on Monad, providing a simple way for users to earn MEV-boosted rewards on their Monad tokens. Users that stake with aPriori can use liquid tokens on a range of DeFi applications to gain extra rewards. ",
  },
  {
    name: "Lucky 777",
    category: AppCategory.Gaming,
    icon: "/images/mainnet/discover/avatar-lucky-777.png",
    banner: "/images/mainnet/discover/banner-lucky-777.png",
    visits: "0",
    link: "/arcade/lucky777",
    bp: "1026_001",
    bpContent: "lucky777",
    isSpotlight: true,
    description: "Spin! Spin! Spin! Earn MON or NFTs by the easiest way",
  },
  {
    name: "Rps",
    category: AppCategory.Gaming,
    icon: "/images/mainnet/discover/avatar-rps.png",
    banner: "",
    visits: "0",
    link: "/arcade/2048",
    bp: "1026_001",
    bpContent: "rps",
    isSpotlight: false,
    description: "",
  },
  {
    name: "Magma",
    category: AppCategory.Staking,
    icon: "/images/mainnet/discover/avatar-magma.png",
    banner: "",
    visits: "0",
    link: "https://www.magmastaking.xyz",
    bp: "1026_001",
    bpContent: "magma",
    isSpotlight: false,
    description: "Magma is a community-owned Liquid Staking Protocol on Monad, designed for equitable token distribution via Points Programs and the with MEV-boosted yield powered by the fastest block engine in crypto. Magma's staking pool allows users to stake their Monad tokens in exchange for liquid staked Monad tokens (gMON).",
  },
  {
    name: "Magic Eden",
    category: AppCategory.NFT,
    icon: "/images/mainnet/discover/avatar-magiceden.png",
    banner: "",
    visits: "0",
    link: "https://magiceden.io",
    bp: "1026_001",
    bpContent: "magiceden",
    isSpotlight: false,
    description: "The leading NFTs trading & minting platform on Monad",
  },
  {
    name: "Levr",
    category: AppCategory.PredictionMarket,
    icon: "/images/mainnet/discover/avatar-levr.png",
    banner: "",
    visits: "0",
    link: "https://app.levr.bet/",
    bp: "1026_001",
    bpContent: "levr",
    isSpotlight: false,
    description: "Leverage Sports Betting with Fully Liquid Positions.",
  },
  {
    name: "Kizzy",
    category: AppCategory.PredictionMarket,
    icon: "/images/mainnet/discover/avatar-kizzy.png",
    banner: "",
    visits: "0",
    link: "https://kizzy.io/",
    bp: "1026_001",
    bpContent: "kizzy",
    isSpotlight: false,
    description: "Kizzy is a social media betting app. Bet on how your favorite influencers and celebrities will perform on Twitter and YouTube.",
  },
  {
    name: "RareBetSports",
    category: AppCategory.PredictionMarket,
    icon: "/images/mainnet/discover/avatar-rarebetsports.png",
    banner: "",
    visits: "0",
    link: "https://rarelink.rarebetsports.io/",
    bp: "1026_001",
    bpContent: "rarebetsports",
    isSpotlight: false,
    description: "Building consumer sports applications powered by the RBS Oracle. Play RareLink and win up to 100x your crypto.",
  },
  {
    name: "Chogstar",
    category: AppCategory.NFT,
    icon: "/images/mainnet/discover/avatar-chogstar.png",
    banner: "",
    visits: "0",
    link: "https://lilchogstars.com/",
    bp: "1026_001",
    bpContent: "chogstar",
    isSpotlight: false,
    description: "Chogstars initial mission is to spread positivity and share unique collectibles that resonate beyond the Monad community while connecting with broader audience. Chogstars strive to craft a creative identity that serves as a beacon of inspiration and reminding everyone that they are, indeed, a star.",
  },
  {
    name: "Timeswap",
    category: AppCategory.Lending,
    icon: "/images/mainnet/discover/avatar-timeswap.png",
    banner: "",
    visits: "0",
    link: "https://app.timeswap.io/",
    bp: "1026_001",
    bpContent: "timeswap",
    isSpotlight: false,
    description: "Timeswap is the first oracleless lending/borrowing protocol — enabling the creation of money markets for ANY ERC20 token.",
  },
  {
    name: "Enjoyoors",
    category: AppCategory.Staking,
    icon: "/images/mainnet/discover/avatar-enjoyoors.png",
    banner: "",
    visits: "0",
    link: "https://app.enjoyoors.xyz/",
    bp: "1026_001",
    bpContent: "enjoyoors",
    isSpotlight: false,
    description: "Unlocks yield on any asset on any chain.",
  },
];
